#!/usr/bin/bash

# Set permissions
chmod 755 -R .

touch ~/.config/mnt.ini  # Create config file if it doesn't exists

# Create a directory where additional files will be stored
sudo mkdir -p /usr/lib/mnt
sudo rm -rf /usr/lib/mnt/langs  # Delete old dictionaries
sudo cp -r langs /usr/lib/mnt/langs  # Copy dictionaries
sudo chmod 755 /usr/lib/mnt -R  # Set permissions

# Fill in the configuration file with data from the template
if [[ -z $(cat ~/.config/mnt.ini) ]] # If config file is empty
then
    source configure
else
    echo -n The configuration file already exists, \
    do you want to overwrite it? [Y/n] "" && read ans
    if [[ $(echo $ans | tr [:upper:] [:lower:]) =~ ^y.*$ ]]
    then
        echo
        ./configure
        echo
    fi
fi

if [[ -z $(command -v mnt) ]]
then
    # Copy program to binary directory
    sudo cp ./mnt /usr/bin/
    sudo chmod 755 /usr/bin/mnt
    echo 'The program has been successfully installed on your computer'
else # If already installed
    echo 'mnt already installed'
fi

# Check dependencies
echo -e "\nChecking dependencies:"
OK=true
for var in whiptail sudo
do
    if [[ -z $(command -v $var) ]]
    then
        OK=false
        echo -e " \033[31m[X] $var\033[0m"
    else
        echo -e " \033[32m[✔] $var\033[0m"
    fi
done

if [[ $OK == true ]]
then 
    echo -e "\nAll dependencies are already installed"
else 
    echo -e "\nThere are missing dependencies. 
Please install them with your distribution's package manager"
fi

exit 0 # The program worked without errors