#!/usr/bin/bash

# Set permissions
chmod 700 -R .
chmod 755 install mnt configure

mkdir ~/.config/mnt/ -p # Create config directory if it doesn't exists
touch ~/.config/mnt/config.ini # Create config file if it doesn't exists

# Fill in the configuration file with data from the template
if [[ -z $(cat ~/.config/mnt/config.ini) ]] # If config file is empty
then
    source configure
else
    echo -n The configuration file already exists, \
    do you want to overwrite it? [Y/n] "" && read ans
    if [[ $(echo $ans | tr [:upper:] [:lower:]) =~ ^y.*$ ]]
    then
        echo
        source configure
        echo
    fi
fi

# Check dependencies
if [[ -z $(command -v whiptail) ]]
then
    echo 'You need to install "whiptail" to your distribution'
fi

if [[ ! -e /usr/bin/mnt ]] # If link doesn't exist
then
    # Create a link for this programm if directory with binary files
    sudo ln ./mnt /usr/bin/mnt
else # If link or file already exists
    if [[ ! -e /usr/sbin/mnt ]] # Trying to install in the sbin folder
    then
        sudo ln ./mnt /usr/sbin/mnt
    else
        echo 'File /usr/bin/mnt already exists'
        exit 1
    fi
fi

echo 'The program has been successfully installed on your computer'
exit 0 # The program worked without errors