#!/usr/bin/bash

# Set permissions
chmod 700 -R .
chmod 755 install mnt configure

touch ~/.config/mnt.ini  # Create config file if it doesn't exists

# Create a directory where additional files will be stored
sudo mkdir -p /usr/lib/mnt
sudo rm -rf /usr/lib/mnt/langs  # Delete old dictionaries
sudo cp -r langs /usr/lib/mnt/langs  # Copy dictionaries
sudo chmod 755 /usr/lib/mnt -R  # Set permissions

# Fill in the configuration file with data from the template
if [[ -z $(cat ~/.config/mnt.ini) ]] # If config file is empty
then
    source configure
else
    echo -n The configuration file already exists, \
    do you want to overwrite it? [Y/n] "" && read ans
    if [[ $(echo $ans | tr [:upper:] [:lower:]) =~ ^y.*$ ]]
    then
        echo
        ./configure
        echo
    fi
fi

# Check dependencies
if [[ -z $(command -v whiptail) ]]
then
    echo 'You need to install "whiptail" to your distribution'
fi

if [[ -z $(command -v mnt) ]]
then
    # Create a link for this programm if directory with binary files
    sudo ln ./mnt /usr/bin/mnt
else # If link or file already installed
    echo 'mnt already installed'
fi

echo 'The program has been successfully installed on your computer'
exit 0 # The program worked without errors