#!/usr/bin/bash

# Function to get section of ini file
function getConfigSection() {
    COUNT=$(grep -A64 -Ex "^\[$1\]$" ~/.config/mnt.ini | grep -Ex "^\[.*\]" -c)
    if [[ "$COUNT" -eq "1" ]]
    then
        grep -A64 -Ex "^\[$1\]$" ~/.config/mnt.ini | grep -Ex "^[^#;].*=.*$" | sed "s/ *= */=/g"
    else
        grep -A64 -Ex "^\[$1\]$" ~/.config/mnt.ini | 
        grep -B64 -Ex "^\[[^${1:0:1}].*\]$" -m1 | grep -Ex "^[^#;].*=.*$" | 
        sed "s/ *= */=/g"
    fi
}

# Get all disk parts with labels with simple regex
DATA=$(lsblk -nio PATH,LABEL | expand | grep -E '^/dev/\w{3}[0-9]+.*(\w|\d)+')
IFS=$'\n' # Only new-line charachter is separator

declare -A assoc # Associative array with parts labels
declare -A parts # Array with disks parts
declare ignore # Array with ignored disks

# Create or touch config file
touch ~/.config/mnt.ini # Create config file if it doesn't exists

# Default variables
mountpoint="/mnt"
language="en"
source <(getConfigSection general) #Get the necessary variables

# Get associations for part labels
for var in $(getConfigSection associations)
do
    label1=$(echo $var | awk -F '=' '{print $1}')
    label2=$(echo $var | awk -F '=' '{print $2}')

    # Make asociations
    assoc[$label1]=$label2
done

# Get list of ignored disks
for var in $(getConfigSection display)
do
    label=$(echo $var | awk -F '=' '{print $1}')
    state=$(echo $var | awk -F '=' '{print $2}')

    if [[ $state == "OFF" ]]
    then
        ignore+=($label)
    fi
done

# Get /dev/name and label of parts
for var in $DATA
do
    dev=$(echo $var | awk '{print $1}')
    label=$(echo $var | awk '{$1=""; print $0}' | sed -r 's/^ *| *$//g')

    if [[ ${ignore[*]} !=  *$label* ]]
    then
        parts[$label]=$dev
    fi
done

width=29 #A whiptail width

# Get the list of disks in the required form
declare -a REQUEST
OFF=0
for var in ${!parts[*]}
do
    # Get the required width
    tmpWidth=$((${#var} + 25))
    if [[ $tmpWidth -gt $width ]]; then width=$tmpWidth; fi

    REQUEST[OFF++]=$var
    REQUEST[OFF++]=${parts[$var]}

    if [[ $(lsblk -o MOUNTPOINT ${parts[$var]}) == *'/'* ]]
    then REQUEST[OFF++]=ON
    else REQUEST[OFF++]=OFF
    fi
done

# Find out which disks need to be mounted and which ones need to be unmounted
QUERY=$(whiptail --title "Disk mount dialog" --checklist \
"Select the disks to mount" $((${#parts[*]}+7)) $width ${#parts[*]} \
${REQUEST[*]} 3>&1 1>&2 2>&3)
if [[ $? != 0 ]]
then
    echo "The operation was canceled by user"
    exit 1
fi

# We mount the marked disks and unmount the unmarked ones
for var in ${!parts[*]}
do
    name=$var

    if [[ ! -z ${assoc[$var]} ]]; then name=${assoc[$var]}; fi

    if [[ $QUERY == *$var* ]]
    then
        sudo mkdir "$mountpoint/$name" -p
        sudo mount ${parts[$var]} "$mountpoint/$name" 2>/dev/null && \
        echo "$var was mounted to $mountpoint/$name"
    else
        sudo umount ${parts[$var]} --quiet && \
        sudo rmdir "$mountpoint/$name" 2>/dev/null && \
        echo "$var was unmounted"
    fi
done

exit 0 # The program worked without errors